# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    # Prefer relative imports for project files
    prefer_relative_imports: true
    
    # Code organization
    directives_ordering: true
    file_names: true
    
    # Documentation
    public_member_api_docs: false
    
    # Design
    use_build_context_synchronously: false
    
    # Riverpod specific
    avoid_dynamic_calls: false
