name: zenn_hack_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI Dependencies
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.0
  
  # Data Classes & Serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # Navigation
  go_router: ^12.1.1
  
  # Storage
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Media
  audioplayers: ^5.2.1
  cached_network_image: ^3.3.0
  
  # Utilities
  logger: ^2.0.2+1
  result_dart: ^1.1.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.6
  
  # Testing
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/
