name: Continuous Integration (flutter_client)
on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: flutter_client
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Read Flutter version from mise.toml
        id: flutter_version
        run: echo "FLUTTER_VERSION=$(grep 'flutter' mise.toml | cut -d '"' -f 2)" >> $GITHUB_ENV

      - name: flutter setup
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: version check
        run: flutter --version

      - name: Decode and generate firebase_options.dart
        env:
          FIREBASE_OPTIONS_BASE64: ${{ secrets.FIREBASE_OPTIONS_BASE64 }}
        run: echo $FIREBASE_OPTIONS_BASE64 | base64 --decode > lib/firebase_options.dart

      - name: install packages
        run: flutter pub get

      - name: flutter analyze
        run: flutter analyze

      - name: flutter test
        run: flutter test
